version: "2"
services:
  app:
    image: odoo:16
    depends_on:
      - db
    restart: always
    tty: true
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo-web-data16:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./twikey_integration:/mnt/extra-addons/twikey_integration
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
volumes:
  odoo-web-data16:
