name: Make release

on:
  workflow_dispatch:
    inputs:
      subversion:
        description: 'Select the tag you want to release'
        default: ''
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Git Version
        id: version
        run: |
          echo "sha_short=$(echo ${{github.sha}} | cut -b -6)" >> $GITHUB_STATE
          echo "::set-output name=sha_short::$(echo ${{github.sha}} | cut -b -6)"

      - name: Build package
        run: |
          sed -i "s/16.0-subver/.${{ github.ref_name }}/"  payment_twikey/__manifest__.py
          sed -i "s/-dev/-${{ steps.version.outputs.sha_short}}/"  payment_twikey/__manifest__.py
          tar -zcvf twikey-odoo-${{ github.ref_name }}.tgz payment_twikey

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: twikey-odoo-${{ github.ref_name }}.tgz
          name: Release ${{ github.ref_name }}
          body: |
            Description of the release.
          draft: true
          replacesArtifacts: true

